[package]
name = "turn_lexer"
version = "0.1.0"
authors = ["Radek Vit <radekvitr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
